# Developed as part of a BSc thesis at the Faculty of Computer Science, Bialystok Univesity of Technology

from typing import List

ALL_RELEVANT_TRAITS: List[str] = [
    "Smile",
    "Laughter",
    "Scowl",
    "Frowning eyebrows",
    "Raising eyebrows",
    "Frequent blinking",
    "Exaggerated eye opening",
    "Exaggerated eye closing",
    "Exaggerated mouth opening",
    "Mouth closed",
    "Lip corners up",
    "Lip corners down",
    "Lips protruded",
    "Lips retracted",
    "Chin moving upwards",
    "Chin moving downwards",
    "Gaze towards interlocutor",
    "Gaze up",
    "Gaze down",
    "Gaze sideways",
    "Nodding",
    "Head moving forward",
    "Head moving backward",
    "Head tilting",
    "Head side-turn",
    "Head shaking",
    "Head up",
    "Hands rubbing",
    "Hands scratching",
    "Hands touching head/body/etc",
    "Hands covering face/mouth/etc",
    "Crossing fingers",
    "Palms up",
    "Arms open",
    "Arms folded",
    "Shrugs",
]
